In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available.")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not availabel. Using CPU.")

GPU is available.
Using GPU: Tesla T4


## Creating a Tensor


In [3]:
# Using Empty
a = torch.empty(2,3)
print(a)

tensor([[0.0000e+00, 0.0000e+00, 4.2039e-45],
        [8.4078e-45, 4.2039e-45, 9.8091e-45]])


In [4]:
# Check Type
type(a)

torch.Tensor

In [5]:
# Using Zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Using rand
torch.rand(2,3)

tensor([[8.3755e-02, 9.5689e-04, 9.6107e-01],
        [1.4608e-01, 8.3240e-01, 6.5010e-01]])

In [8]:
# Using of manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# Other ways

# arange
print("Using arange ->",torch.arange(0,10,2))

# linspace
print("Using linspace ->", torch.linspace(0,10,10))

# eye
print("Using eye ->", torch.eye(5))

# full
print("Using full ->", torch.full((3,3), 5))

Using arange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[        0, 286670336,         0],
        [        0,         0,         0]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [17]:
# Find data type
x.dtype

torch.int64

In [18]:
# Assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1, 2, 3], dtype=torch.int64)

tensor([1, 2, 3])

In [20]:
# Using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |



## Mathematical operations
### 1. Scalar operation

In [21]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [22]:
# addition
print(x + 2)

# subtraction
print(x - 2)

# multiplication
print(x * 3)

# divison
print(x / 3)

# int divison
print((x * 100) // 3)

# mod

print(((x * 100) // 3) % 2)

# power
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### 2. Element wise operation

In [23]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [24]:
# add
print(a + b)

# subtraction
print(a - b)

# multiplication
print(a * b)

# divison
print(a / b)

# power
print(a ** b)

# mod
print(a % b)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])
tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])


In [25]:
c = torch.tensor([1, -2, -3, 4])


In [26]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
# neg
torch.neg(c)

tensor([-1,  2,  3, -4])

In [28]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [29]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [30]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [31]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [32]:
# clamp
torch.clamp(d, min=2, max =3.5)

tensor([2.0000, 2.3000, 3.5000, 3.5000])

### 3. Reduction operation

In [33]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [34]:
# sum
print(torch.sum(e))

# sum along columns
print(torch.sum(e, dim=0))

# sum along rows
print(torch.sum(e, dim=1))


tensor(24.)
tensor([ 8.,  0., 16.])
tensor([15.,  9.])


In [35]:
# mean
print(torch.mean(x))

# mean along column
torch.mean(x, dim=0)

tensor(0.7048)


tensor([0.5650, 0.8445])

In [36]:
# median
print(torch.median(e))

# median along row
print(torch.median(e, dim=1))

tensor(0.)
torch.return_types.median(
values=tensor([7., 0.]),
indices=tensor([2, 1]))


In [37]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(0.)


In [38]:
# product
print(torch.prod(e))

tensor(0.)


In [39]:
# standard deviation
print(torch.std(e))

tensor(4.4272)


In [40]:
# variance
print(torch.var(e))

tensor(19.6000)


In [41]:
# argmax
torch.argmax(e)

tensor(5)

In [42]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [43]:
f = torch.randint(size=(2,3), low=1, high=10)
g = torch.randint(size=(3,2), low=1, high=10)

print(f)
print(g)

tensor([[3, 7, 7],
        [4, 9, 3]])
tensor([[7, 6],
        [7, 4],
        [1, 7]])


In [44]:
# matrix multiplication
torch.matmul(f, g)

tensor([[77, 95],
        [94, 81]])

In [45]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [46]:
# transpose
torch.transpose(f, 1, 0)

tensor([[3, 4],
        [7, 9],
        [7, 3]])

In [47]:
h = torch.randint(size=(3,3), low=0,high=10,dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [48]:
# determinant
torch.det(h)

tensor(-110.)

In [49]:
# inverse

torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [50]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [51]:
# greater than
print(i > j)

# less than
print(i < j)

# equal to
print(i == j)

# not equal to
print(i != j)

# greater than equal to
print(i >= j)

# less than equal to
print(i <= j)

tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])


### 6. Special functions

In [52]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [53]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [54]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [55]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [56]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [57]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [58]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [59]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [60]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [61]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [62]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [63]:
b = a
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [64]:
a[0] = 1
b

tensor([[1.0000, 1.0000, 1.0000],
        [0.7668, 0.1659, 0.4393]])

In [65]:
id(a) == id(b)

True

In [66]:
c = a.clone()

In [67]:
a[0][0] = 2
a

tensor([[2.0000, 1.0000, 1.0000],
        [0.7668, 0.1659, 0.4393]])

In [68]:
c

tensor([[1.0000, 1.0000, 1.0000],
        [0.7668, 0.1659, 0.4393]])

In [69]:
id(c) == id(a)

False

### Tensor Operation on GPU

In [71]:
torch.cuda.is_available()

True

In [73]:
device = torch.device('cuda')

In [74]:
# Creating a new tensor in GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [75]:
# Moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [77]:
b = a.to(device)
b + 5

tensor([[5.2243, 5.8935, 5.0497],
        [5.1780, 5.3011, 5.1893]], device='cuda:0')

In [80]:
import time

# Define the size of the matrices
size = 10000

# Create random matrices on CPU
matric_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matric_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrix to GPU
matrix_gpu1 = matric_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeed-up (CPU Time / GPU Time):", cpu_time / gpu_time)


Time on CPU: 26.9590 seconds
Time on GPU: 0.0004 seconds

Speed-up (CPU Time / GPU Time): 73329.60311284047


### Reshaping Tensors

In [81]:
a = torch.ones(4,4)
a


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [82]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [83]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
b = torch.rand(2,3,4)
b

tensor([[[0.0175, 0.1639, 0.4733, 0.1569],
         [0.3070, 0.1020, 0.1914, 0.9407],
         [0.5304, 0.5252, 0.6272, 0.6186]],

        [[0.8889, 0.1310, 0.2608, 0.3661],
         [0.9643, 0.2575, 0.0298, 0.6887],
         [0.2672, 0.4914, 0.4353, 0.3025]]])

In [88]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [91]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [93]:
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

### NumPy and PyTorch

In [94]:
import numpy as np

In [95]:
a = torch.rand([1,2,3])
a

tensor([[[0.2818, 0.8194, 0.2544],
         [0.7075, 0.1863, 0.5048]]])

In [97]:
b = a.numpy()
b

array([[[0.28177238, 0.819355  , 0.25437438],
        [0.70753926, 0.18627113, 0.50481397]]], dtype=float32)

In [98]:
type(b)

numpy.ndarray

In [99]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [100]:
torch.from_numpy(c)

tensor([1, 2, 3])