In [1]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [2]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward Pass
# model.forward(features)

model(features)

tensor([[0.5171],
        [0.5242],
        [0.5127],
        [0.5251],
        [0.5123],
        [0.5247],
        [0.5166],
        [0.5198],
        [0.5081],
        [0.5187]], grad_fn=<SigmoidBackward0>)

In [13]:
# Show Model Weights
model.network[2].weight

Parameter containing:
tensor([[-0.4379, -0.1787,  0.2720]], requires_grad=True)

In [8]:
model.network[2].weight

Parameter containing:
tensor([[-0.4379, -0.1787,  0.2720]], requires_grad=True)

In [9]:
!pip install torchinfo

In [12]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00