In [9]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import Dataset, DataLoader

In [3]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [4]:
print(X.shape)
print(y.shape)

(10, 2)
(10,)


In [6]:
# Convert the data PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

/tmp/ipython-input-904047727.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)


In [11]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [12]:
dataset = CustomDataset(X,y)

In [13]:
len(dataset)

10

In [14]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [15]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [17]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*100)

tensor([[-2.8954,  1.9769],
        [-1.1402, -0.8388]])
tensor([0, 0])
----------------------------------------------------------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.0683, -0.9701]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.7273, -1.1858]])
tensor([1, 1])
----------------------------------------------------------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.7206, -0.9606]])
tensor([1, 0])
----------------------------------------------------------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.8997,  0.8344]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
